@include('partials.plantilla.head')
@include('partials.plantilla.header')
@include('partials.plantilla.about')
@include('partials.plantilla.vegetable')
@include('partials.plantilla.contact')
@include('partials.plantilla.footer')